name: Test Go Code

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22.6
      - name: Build
        run: go build hash-based/load_balancer.go && go build round-robin/load_balancer.go  
      - name: Test
        run: cd hash-based ;go test -v ; cd ../round-robin/; go test -v
